name: Cypress Tests
on:
  push:
    branches: [ master ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands
        run: |
          echo "hello world"
          echo "Action Associated succesfully"
